#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

set +e
echo "select count(*) from customers" | psql > /dev/null 2>&1
if [ "$?" -eq 0 ]; then
    exit 0
fi

curl https://raw.githubusercontent.com/pthom/northwind_psql/5f9ba34aa1d980392685042037b0b1112d01bd32/northwind.sql | psql

echo "alter table orders add column order_timestamp timestamp" | psql
echo "update orders set order_timestamp = concat(order_date, ' ', floor(random() * 24)::varchar, ':', floor(random() * 60)::varchar, ':', floor(random() * 60)::varchar)::timestamp" | psql
echo "alter table orders drop column order_date" | psql
